#%RAML 1.0
---
title: StraenWeb
baseUri: http://straen-app.com/api/{version}
mediaType: application/json
version: v1
/update_status:
    description: Used by the mobile application to update it's status.
    get:
    post:
        responses:
            200: Empty string
            500: An internal exception was thrown.
/activity_track:
    description: Returns the activity track as a collection of JSON objects.
    get:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            401: Failed authentication. The session token was expired, invalid, or not provided.
            500: An internal exception was thrown.
    post:
/activity_metadata:
    description: Returns the activity metadata as a collection of JSON objects.
    get:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            500: An internal exception was thrown.
    post:
/update_activity_metadata:
    description:
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/login:
    description: Authenticates a username and password.
    get:
    post:
        responses:
            200:
            401: Failed authentication. The username and password were invalid, or not provided.
            500: An internal exception was thrown.
/create_login:
    description: Creates a new account.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            401: Failed authentication. The username and password were not provided or did not meet security requirements.
            500: An internal exception was thrown.
/login_status:
    description: Determines if the current user has a valid session token.
    get:
        responses:
            200: Empty string
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
/logout:
    description: Terminates the current user's session.
    get:
    post:
        responses:
            200: Empty string
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/update_email:
    description: Updates the user's email address.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/update_password:
    description: Updates the user's password.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/delete_gear:
    description: Removes the current user's gear (all of it).
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/delete_activities:
    description: Removes the current user's activity data (all of it).
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/delete_user:
    description: Removes the current user and all associated data.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/list_all_activities:
    description: Returns a list of JSON objects describing all of the user's activities and the activities of the users being followed.
    get:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
/list_my_activities:
    description: Returns a list of JSON objects describing all of the user's activities.
    get:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
/delete_activity:
    description: Removes the specified activity.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/add_activity: Creates a new activity from user-provided data.
    description:
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/upload_activity_file:
    description: Creates a new activity from data contained with the appended file.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/add_tag_to_activity:
    description: Adds a tag to an activity.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/delete_tag_from_activity:
    description: Deletes a tag from an activity.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/list_matched_users:
    description: Lists user's whose usernames match the search criteria. Results are limited to the first 100 users.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/list_users_following:
    description: Lists the users you are following.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/list_users_followed_by:
    description: Lists the users who are following you.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/request_to_follow:
    description: Sends a request to follow another user.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/unfollow:
    description: Removes a user from the list of users being followed by the logged in user.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/export_activity:
    description: Returns the activity in the specified format.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/claim_device:
    description: Associates the device specified by the unique identifier with the logged in user's account.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/create_tag:
    description: Creates a tag for the specified activity.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/delete_tag:
    description: Deletes a tag from the specified activity.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/list_tags:
    description: Lists the tags for the specified activity.
    get:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
/create_comment:
    description: Adds a comment to the specified activity.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/list_comments:
    description: Lists comments for the specified activity.
    get:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
/create_gear:
    description: Creates a new gear record for the current user, such as a new bike or pair of shoes.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/list_gear:
    description: Lists gear associated with the current user.
    get:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
/update_gear:
    description: Updates the gear name or description.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/delete_gear:
    description: Delete's the specified gear record and all associated service records.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/create_service_record:
    description: Appends service information for a piece of gear (intended for tracking bicycle service data).
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/delete_service_record:
    description: Deletes service informatio for a piece of gear.
    get:
    post:
        responses:
            200:
            401:
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/add_gear_to_activity:
    description: Tags the specified activity with the gear.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/update_settings:
    description:
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/update_profile:
    description:
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/update_visibility:
    description: Updates activity visibility.
    get:
    post:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/refresh_analysis:
    description: Schedules the specified activity for (re)analysis.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/generate_workout_plan:
    description: Schedules workout plan generation. Will generate workouts for the week.
    get:
    post:
        responses:
            200: Empty string
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
/list_workouts:
    description: Lists scheduled workouts.
    get:
        responses:
            200: A JSON-formatted description of all scheduled workouts for the current user.
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
/get_workout_description:
    description:
    get:
        responses:
            200: A JSON string containing the details of the workout.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
/get_workout_ical_url:
    description:
    get:
        responses:
            200: A URL string.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
/get_location_description:
    description:
    get:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
/activity_id_from_hash:
    description:
    get:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
/activity_hash_from_id:
    description:
    get:
        responses:
            200:
            400: Malformed request. Either required parameters were missing or the supplied parameters were malformed.
            403: Failed authentication. The user is not logged in.
            500: An internal exception was thrown.
    post:
