broker_url = 'amqp://'
result_backend = 'mongodb'
task_serializer = 'json'
result_serializer = 'json'
accept_content = ['json']
enable_utc = True
broker_pool_limit = 1
celery_acks_late = True
worker_prefetch_multiplier = 1
worker_concurrency = 1
broker_transport_options = {'confirm_publish': True}
