# Copyright 2017 Michael J Simms
"""Key strings from key/value pairs returned by the app"""

USERNAME_KEY = "username"
PASSWORD_KEY = "password"
PASSWORD1_KEY = "password1"
PASSWORD2_KEY = "password2"
DEVICE_KEY = "device"
REALNAME_KEY = "realname"
HASH_KEY = "hash"
DEVICES_KEY = "devices"

NAME_KEY = "Name"
TIME_KEY = "Time"
DISTANCE_KEY = "Distance"
CADENCE_KEY = "Cadence"
CURRENT_SPEED_KEY = "Current Speed"
AVG_SPEED_KEY = "Avg. Speed"
MOVING_SPEED_KEY = "Moving Speed"
HEART_RATE_KEY = "Heart Rate"
CURRENT_PACE_KEY = "Current Pace"
POWER_KEY = "Power"
SETS_KEY = "Sets"

LOCATION_LAT_KEY = "latitude"
LOCATION_LON_KEY = "longitude"
LOCATION_ALT_KEY = "altitude"
LOCATION_TIME_KEY = "time"

ACTIVITY_ID_KEY = "activity_id"
ACTIVITY_TYPE_KEY = "activity_type"
ACTIVITY_DEVICE_STR_KEY = "device_str"
ACTIVITY_LOCATIONS_KEY = "locations"
ACTIVITY_NAME_KEY = "name"
ACTIVITY_TIME_KEY = "time"
ACTIVITY_VISIBILITY_KEY = "visibility"
ACTIVITY_COMMENTS_KEY = "comments"

TYPE_RUNNING_KEY = "Running"
TYPE_CYCLING_KEY = "Cycling"
TYPE_SWIMMING_KEY = "Swimming"
TYPE_PULL_UPS_KEY = "Pull Ups"
